package com.doatec.model.account;

public enum AcaoTipo {
    APROVAR_DOACAO,
    REJEITAR_DOACAO,
    ALTERAR_STATUS_DOACAO,
    APROVAR_SOLICITACAO,
    REJEITAR_SOLICITACAO,
    CONCLUIR_SOLICITACAO,
    RESPONDER_SUPORTE,
    DESATIVAR_USUARIO,
    REATIVAR_USUARIO
}